### PR TITLE
Use 'log' library across project

### PR DESCRIPTION
**Pull request by chocol4te**
This PR adds 'log' to the libraries, and uses 'simplelogger' in the binaries to display the information.

### CODE REVIEW

**Comment by alex-konovalov** [comment]
Let's merge as soon as CI is restored back and tests pass.

**Comment by chocol4te** [comment]
@alex-konovalov Sorry again for all the fuss, but Travis CI needs to be authorised by "use-standrewscs" before I can reconfigure it. I made a request, but I'm not sure where one would accept it, did you get a notification?

**Comment by alex-konovalov** [comment]
I thought I activated it yesterday ?
Screenshot 2020-01-17 at 14 02 50

**Comment by chocol4te** [comment]
🤦‍♂️ my bad, again, I was looking at "travis-ci.com" not "travis-ci.org". It's still not listed under my account however, any ideas?

Screenshot 2020-01-17 at 14 15 29

**Comment by alex-konovalov** [comment]
Sync account and refresh the page? We observed with my collaborator this morning that even after syncing the account, after adding a new repo, it did not refresh automatically.

**Comment by alex-konovalov** [comment]
It is at https://travis-ci.org/rse-standrewscs/shallow-water - I've just triggered a fresh build

**Comment by alex-konovalov** [comment]
Codecov will appear at https://codecov.io/gh/rse-standrewscs/shallow-water

**Comment by chocol4te** [comment]
Strange, it's still not appearing, but with that link I can trigger builds/change settings. Excellent, I'll try and fix the failing builds.

**Pull request merged**
