### PR TITLE
Deploy documentation to GitHub Pages

### PR DESCRIPTION
**Pull request by chocol4te**

### CODE REVIEW

**Comment by alex-konovalov** [comment]
Nice! What's the URL? The one in the repo description (https://rse-standrewscs.github.io/shallow-water/) does not work...

**Comment by chocol4te** [comment]
It should be [https://rse-standrewscs.github.io/shallow-water/shallow_water/index.html](https://rse-standrewscs.github.io/shallow-water/shallow_water/index.html), it's possible to add an `index.html` at `https://rse-standrewscs.github.io/shallow-water/index.html` to redirect, but I thought it would just be easier to update the link in the README (https://github.com/rse-standrewscs/shallow-water/commit/83dbef1d04668ed6d63d367a79eda1fac067afb2).

**Comment by alex-konovalov** [comment]
Thanks - I've updated the URL in the repo description too.

**Comment by chocol4te** [comment]
Thank you! I'd forgotten to do that!

**Pull request merged**
